import Footer from './components/Footer';
import Navbar from './components/Navbar';
import ScrollToBottomTop from './components/ScrollToTopButton';
import './globals.css';
import ReduxProvider from './redux/provider';

export const metadata = {
  title: '베시시',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/images/logo.png' />
      </head>
      <body className='text-sm'>
        <ReduxProvider>
          <Navbar />
          <main className='w-full mx-auto pt-20 mb-14'>{children}</main>
          <ScrollToBottomTop />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
